apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.12.4
      helm:
        values: |
          installCRDs: true
    - repoURL: git@github.com:amkartashov/gf-k8s.git
      targetRevision: main
      path: state/gullfaxi/system/cert-manager/manifests/
