dependencies:
- name: graylog
  version: '1.6.2'
  repository: '@stable'
- name: mongodb
  version: '7.8.9'
  repository: '@stable'
- name: elasticsearch
  version: '7.6.1'
  repository: https://helm.elastic.co
- name: fluent-bit
  version: '2.8.11'
  repository: '@stable'
