dependencies:
- name: graylog
  version: '1.3.9'
  repository: '@stable'
- name: mongodb
  version: '7.4.5'
  repository: '@stable'
- name: elasticsearch
  version: '7.4.1'
  repository: https://helm.elastic.co
