# don't install as graylog deps, because versions are outdated
tags:
  install-elasticsearch: false
  install-mongodb: false

mongodb:
  nameOverride: mongodb
  fullnameOverride: mongodb
  usePassword: false
  persistence:
    existingClaim: mongodb

elasticsearch:
  nameOverride: elasticsearch
  fullnameOverride: elasticsearch
  imageTag: '6.8.4'
  replicas: 1
  minimumMasterNodes: 1
  volumeClaimTemplate:
    volumeName: elasticsearch

graylog:
  nameOverride: graylog
  fullnameOverride: graylog
  graylog:
    replicas: 1
    persistence:
      enabled: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - graylog.gorilych.ru
      tls:
      - hosts:
        - graylog.gorilych.ru
        secretName: graylog-tls
    mongodb:
      uri: mongodb://mongodb:27017/graylog
    elasticsearch:
      hosts: http://elasticsearch-master:9200
    plugins:
    - name: graylog-plugin-auth-sso-3.1.0.jar
      url: https://github.com/Graylog2/graylog-plugin-auth-sso/releases/download/3.1.0/graylog-plugin-auth-sso-3.1.0.jar

