# don't install as graylog deps, because versions are outdated
tags:
  install-elasticsearch: false
  install-mongodb: false

mongodb:
  nameOverride: mongodb
  fullnameOverride: mongodb
  usePassword: false
  persistence:
    existingClaim: mongodb

graylog:
  nameOverride: graylog
  fullnameOverride: graylog
  graylog:
    replicas: 1
    persistence:
      enabled: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - graylog.gorilych.ru
      tls:
      - hosts:
        - graylog.gorilych.ru
        secretName: graylog-tls
    mongodb:
      uri:
        mongodb://mongodb:27017/graylog

