apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-k8s-stack
  labels:
    stack: observability
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics-k8s-stack
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.18.1
      helm:
        values: |
          # https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml

          # disable dependencies, as they are installed separately
          victoria-metrics-operator: { enabled: false }
          kube-state-metrics: { enabled: false }
          prometheus-node-exporter: { enabled: false }
          grafana: { enabled: false }
          crds: { enabled: false }

          # deployed separately
          vmsingle: { enabled: false }
          vmagent: { enabled: false }

          # don't need it yet
          alertmanager: { enabled: false }
          vmalert: { enabled: false }
          defaultRules: { create: true }
