nginx-ingress:
  controller:
    metrics:
      enabled: true
    service:
      omitClusterIP: true
      type: NodePort
      nodePorts:
        # port forwarding on router
        http: 30080
        https: 30443
  defaultBackend:
    service:
      omitClusterIP: true
