loki:
  #extraArgs:
  #  log.level: debug
  nameOverride: loki
  fullnameOverride: loki
  serviceAccount:
    create: true
    annotations:
      iam.gke.io/gcp-service-account:  loki-sa@projectid.iam.gserviceaccount.com # will be updated in parameters
  serviceMonitor:
    enabled: true
    interval: 10s
    scrapeTimeout: 5s
  resources:
    limits:
      cpu: 150m
      #memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  persistence:
    enabled: true
    size: 10Gi
    existingClaim: loki

promtail:
  nameOverride: promtail
  fullnameOverride: promtail
  serviceMonitor:
    enabled: true
    interval: 10s
    scrapeTimeout: 5s
  loki:
    serviceName: loki
  resources:
    limits:
      cpu: 100m
      #memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
