apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: san-gorilych-ru-certificate
  namespace: default
spec:
  secretName: san-gorilych-ru-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: gorilych.ru
  dnsNames:
  - gorilych.ru
  - router.gorilych.ru
