oauth2-proxy:
  config:
    existingSecret: oauth2-proxy
  extraArgs:
    provider: github
    cookie-domain: .gorilych.ru
    whitelist-domain: .gorilych.ru
  authenticatedEmailsFile:
    enabled: true
    restricted_access: |-
      gorilych@gmail.com
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - oauth2.gorilych.ru
    tls:
    - hosts:
      - oauth2.gorilych.ru
      secretName: san-gorilych-ru-tls

