oauth2-proxy:
  config:
    existingSecret: oauth2-proxy
    configFile: |-
      email_domains = []
      upstreams = [ "file:///dev/null" ]
  extraArgs:
    provider: github
    cookie-domain: .gorilych.ru
    whitelist-domain: .gorilych.ru
    set-xauthrequest: true
  authenticatedEmailsFile:
    enabled: true
    restricted_access: |-
      gorilych@gmail.com
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - oauth2.gorilych.ru
    tls:
    - hosts:
      - oauth2.gorilych.ru
      secretName: oauth2-gorilych-ru-tls

