apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: websites
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: websites
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:amkartashov/gf-k8s.git
    targetRevision: main
    path: state/gullfaxi/apps/websites/manifests/
