apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealedsecrets
commonLabels:
  app.kubernetes.io/name: sealedsecrets
  app.kubernetes.io/version: 0.9.2
  app.kubernetes.io/managed-by: argocd
resources:
- namespace.yaml
# from https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.2/controller.yaml
- controller.yaml
