apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  labels:
    stack: observability
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-state-metrics
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      targetRevision: 5.13.0
      helm:
        values: |
          # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
          prometheus:
            monitor:
              enabled: true
              honorLabels: true
