prometheus-operator:
  prometheus:
    enabled: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  defaultRules:
    create: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
