apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.logging:3100
      version: 1
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-operator-prometheus.monitoring:9090/
      version: 1
