# have to add repo because oci:// prefix is not supported in repoURL
# https://github.com/argoproj/argo-cd/issues/10823
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-operator
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: grafana-operator
  type: helm
  enableOci: "true"
  url: ghcr.io/grafana-operator/helm-charts
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  labels:
    stack: observability
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-operator
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: ghcr.io/grafana-operator/helm-charts
    chart: grafana-operator
    targetRevision: v5.4.1
    helm:
      values: |
        # https://github.com/grafana-operator/grafana-operator/tree/master/deploy/helm/grafana-operator
