apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      instance: grafana
  datasource:
    name: victoria
    type: prometheus
    access: proxy
    url: http://victoria.victoria-metrics:8429
    isDefault: true
    editable: false
