apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
spec:
  selectAllByDefault: true
  replicaCount: 1
  remoteWrite:
    - url: http://victoria:8429/api/v1/write
