apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  labels:
    stack: observability
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:amkartashov/gf-k8s.git
    targetRevision: main
    path: state/gullfaxi/system/observability/victoria-metrics/manifests/

