---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshct
  labels:
    app: sshct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshct
  template:
    metadata:
      labels:
        app: sshct
    spec:
      hostNetwork: true
      volumes:
      - name: home
        hostPath:
          path: /home
          type: DirectoryOrCreate
      - name: containerdsock
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
      containers:
      - name: sshct
        securityContext:
          privileged: true
        image: ghcr.io/amkartashov/sshct:v4.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: CT_SSH_PORT
          value: "30810"
        - name: CT_TIMEZONE
          value: Asia/Novosibirsk
        - name: CT_LOCALE
          value: ru_RU.UTF-8
        - name: CT_USERGROUPS
          value: docker:999
        volumeMounts:
        - mountPath: /home
          name: home
        - mountPath: /run/containerd/containerd.sock
          name: containerdsock
