apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    path: apps/services
    repoURL: git@github.com:amkartashov/gf-k8s
