apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpn
  namespace: argocd
spec:
  destination:
    namespace: vpn
    server: https://kubernetes.default.svc 
  project: default
  source:
    path: apps/system/vpn
    repoURL: git@github.com:amkartashov/gf-k8s
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
