apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: git@github.com:amkartashov/gf-k8s.git
      targetRevision: main
      path: state/gullfaxi/system/argocd/manifests
    # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 5.45.0
      helm:
        valueFiles:
          - $values/state/gullfaxi/system/argocd/values.yaml
    - repoURL: git@github.com:amkartashov/gf-k8s.git
      targetRevision: main
      ref: values
