---
# have to add repo because oci:// prefix is not supported in repoURL
# https://github.com/argoproj/argo-cd/issues/10823
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: forgejo-oci-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami
  type: helm
  enableOci: "true"
  url: codeberg.org/forgejo-contrib
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: codeberg.org/forgejo-contrib
      chart: forgejo
      targetRevision: 0.12.1
      helm:
        valuesObject:
          memcached:
            enabled: false
          postgresql:
            enabled: false
          test:
            enabled: false
          ingress:
            enabled: true
            className: nginx
            annotations:
              kubernetes.io/tls-acme: "true"
            hosts:
              - host: git.ioot.xyz
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: forgejo-tls
                hosts:
                  - git.ioot.xyz
          gitea:
            admin:
              username: admin
              password: reset_in_argocd
              email: "a@ioot.xyz"
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
    - repoURL: git@github.com:amkartashov/gf-k8s.git
      targetRevision: main
      path: state/gullfaxi/apps/forgejo/manifests
