---
# have to add repo because oci:// prefix is not supported in repoURL
# https://github.com/argoproj/argo-cd/issues/10823
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: forgejo-oci-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami
  type: helm
  enableOci: "true"
  url: codeberg.org/forgejo-contrib
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: codeberg.org/forgejo-contrib
    chart: forgejo
    targetRevision: 0.12.1
    helm:
      values: |
        memcached:
          enabled: true
        postgresql:
          enabled: false
        test:
          enabled: false
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - host: git.ioot.xyz
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: forgejo-tls
              hosts:
                - git.ioot.xyz
        gitea:
          admin:
            username: amkartashov
            # password: reset_in_argocd
            email: "a@ioot.xyz"
          oauth:
            - name: GitHub
              provider: github
          config:
            database:
              DB_TYPE: postgres
              HOST: postgresql-rw
              NAME: gitea
              USER: gitea
              # PASSWD: reset_in_argocd
            service:
              DISABLE_REGISTRATION: "true"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
