prometheus-operator:
  nameOverride: prometheus-operator
  fullnameOverride: prometheus-operator
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    tlsProxy:
      enabled: false
    serviceMonitor:
      selfMonitor: false
  prometheus:
    enabled: true
    serviceMonitor:
      selfMonitor: false
    prometheusSpec:
      replicas: 1
      securityContext:
        runAsUser: 1000
      walCompression: true
      serviceMonitorSelector:
        any: true
      serviceMonitorNamespaceSelector:
        any: true
      storage:
        volumeClaimTemplate:
          spec:
            volumeName: prometheus
            resources:
              requests:
                storage: 10Gi
  alertmanager:
    enabled: false
  defaultRules:
    create: false
  kubelet:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
# because of https://github.com/helm/helm/issues/4490
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
grafana:
  enabled: false
