prometheus-operator:
  nameOverride: prometheus-operator
  fullnameOverride: prometheus-operator
  prometheus:
    enabled: true
    prometheusSpec:
      version: v2.14.0
      replicas: 1
      securityContext:
        runAsUser: 1000
      walCompression: true
      serviceMonitorSelector:
        any: true
      serviceMonitorNamespaceSelector:
        any: true
      storage:
        volumeClaimTemplate:
          spec:
            volumeName: prometheus
            resources:
              requests:
                storage: 10Gi
  grafana:
    nameOverride: grafana
    fullnameOverride: grafana
    defaultDashboardsEnabled: false
    enabled: true
    # secret grafana should be created manually
    # it should contain:
    #   admin-user
    #   admin-password
    #   GF_AUTH_GITHUB_CLIENT_SECRET
    admin:
      existingSecret: grafana
    envFromSecret: grafana
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - grafana.gorilych.ru
      tls:
      - hosts:
        - grafana.gorilych.ru
        secretName: grafana-tls
    persistence:
      enabled: true
      type: pvc
      existingClaim: grafana
    grafana.ini:
      server:
        root_url: https://grafana.gorilych.ru
      auth.github:
        enabled: true
        allow_sign_up: false
        client_id: 6494b9ed39a915d9ac20
        # client_secret: in grafana secret
        scopes: user:email,read:org
        auth_url: https://github.com/login/oauth/authorize
        token_url: https://github.com/login/oauth/access_token
        api_url: https://api.github.com/user
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-operated:9090
          editable: false
  alertmanager:
    enabled: false
  defaultRules:
    create: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
# because of https://github.com/helm/helm/issues/4490
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
grafana:
  enabled: true
