apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # default is for app-of-apps applications
  # others should go to corresponding projects: system, apps, etc
  project: default
  source:
    repoURL: git@github.com:amkartashov/gf-k8s.git
    path: state/gullfaxi
    targetRevision: master
    directory:
      recurse: true
      # manifests dir allows for nested manifests,
      # application dir allows for stand-alone application
      exclude: "{*/manifests/*,*/application/*}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
