apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  labels:
    stack: observability
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: promtail
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.15.2
      helm:
        values: |
          # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
          config:
            clients:
              - url: http://loki.loki:3100/loki/api/v1/push
