apiVersion: apps/v1
kind: Deployment
metadata:
  name: timemachine
  labels:
    app: timemachine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timemachine
  template:
    metadata:
      labels:
        app: timemachine
    spec:
      hostNetwork: true
      hostname: timemachine
      volumes:
        - name: timemachine
          hostPath:
            path: /home/backup/timemachine
            type: DirectoryOrCreate
      containers:
        - name: timemachine
          image: mbentley/timemachine:smb
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: timemachine
          env:
            - name: CUSTOM_SMB_CONF
              value: "false"
            - name: CUSTOM_USER
              value: "false"
            - name: DEBUG_LEVEL
              value: "1"
            - name: MIMIC_MODEL
              value: "TimeCapsule8,119"
            - name: EXTERNAL_CONF
              value: ""
            - name: HIDE_SHARES
              value: "no"
            - name: TM_USERNAME
              value: "timemachine"
            - name: TM_GROUPNAME
              value: "timemachine"
            - name: TM_UID
              value: "1000"
            - name: TM_GID
              value: "1000"
            - name: SET_PERMISSIONS
              value: "false"
            - name: SHARE_NAME
              value: "TimeMachine"
            - name: SMB_INHERIT_PERMISSIONS
              value: "no"
            - name: SMB_NFS_ACES
              value: "yes"
            - name: SMB_METADATA
              value: "stream"
            - name: SMB_PORT
              value: "445"
            - name: SMB_VFS_OBJECTS
              value: "acl_xattr fruit streams_xattr"
            - name: VOLUME_SIZE_LIMIT
              value: "0"
            - name: WORKGROUP
              value: "WORKGROUP"
          volumeMounts:
            - mountPath: /opt/timemachine
              name: timemachine
