apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubevirt
    server: https://kubernetes.default.svc 
  project: default
  source:
    path: apps/system/kubevirt
    repoURL: git@github.com:gorilych/gf-k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
