apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: v0.0.24
    path: deploy/chart/local-path-provisioner
    helm:
      values: |
        # https://github.com/rancher/local-path-provisioner/blob/v0.0.24/deploy/chart/local-path-provisioner/values.yaml
        storageClass:
          defaultClass: true
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /data/local-path-provisioner
