cilium:
  kubeProxyReplacement: strict
  k8sServiceHost: 192.168.1.8
  k8sServicePort: 6443
  operator:
    replicas: 1
  bpf:
    masquerade: true
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
